[package]
name = "shared"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true


[dependencies]
config = { path = "../config" }

axum = "0.8.9"
sqlx = { version = "0.9.0", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
] }